# Configuracion de Nginx para servir la app de Angular.
server {
    listen 80;

    # Carpeta donde estan los archivos de la app.
    root /usr/share/nginx/html;
    index index.html;

    # Proxy para llamadas API al backend Spring Boot
    location ~ ^/(productos|categorias|usuarios|auth|perfiles|carritos|detalle-carritos|detalle-pedidos|pedidos|pagos|envios|resenas|planes|plan-cuotas) {
        proxy_pass http://backend:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # IMPORTANTE para Angular: como es una "single page application",
    # cualquier ruta (ej: /productos, /pedidos) debe devolver index.html
    # y dejar que Angular se encargue de mostrar la pagina correcta.
    location / {
        try_files $uri $uri/ /index.html;
    }
}
